package export

import (
	"fmt"
	"strings"
	"time"

	"github.com/prettyletto/omarchy-themegen/internal/theme"
)

func GenerateREADME(tm *theme.ThemeModel) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s\n\n", tm.Name))

	b.WriteString("Generated by [omarchy-themegen](https://github.com/prettyletto/omarchy-themegen).\n\n")

	b.WriteString("## Generation Summary\n\n")
	b.WriteString(fmt.Sprintf("- Mode: %s\n", tm.Mode))
	if tm.DirectionID > 0 {
		b.WriteString(fmt.Sprintf("- Direction: %d (%s)\n", tm.DirectionID, tm.DirectionLabel))
	} else {
		b.WriteString("- Direction: Static (default palette)\n")
	}
	if tm.LightMode {
		b.WriteString("- Mode: light\n")
	} else {
		b.WriteString("- Mode: dark\n")
	}
	b.WriteString(fmt.Sprintf("- Generator version: %s\n", tm.Version))

	if tm.Mode == "component-mix" && len(tm.GroupSelections) > 0 {
		b.WriteString("- Group selections:\n")
		for gid, did := range tm.GroupSelections {
			b.WriteString(fmt.Sprintf("  - %s → direction %d\n", gid, did))
		}
	}
	if len(tm.Overrides) > 0 {
		b.WriteString("- Per-surface overrides:\n")
		for surf, did := range tm.Overrides {
			b.WriteString(fmt.Sprintf("  - %s → direction %d\n", surf, did))
		}
	}
	b.WriteString("\n")

	b.WriteString("## Installation of omarchy-themegen\n\n")
	b.WriteString("```bash\n")
	b.WriteString("go install github.com/prettyletto/omarchy-themegen@latest\n")
	b.WriteString("```\n\n")

	b.WriteString("## CLI Usage\n\n")
	b.WriteString("Open the interactive TUI to generate and select a theme:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# Open the keyboard-only TUI\n")
	b.WriteString("omarchy-themegen <path-to-image>\n")
	b.WriteString("```\n\n")
	b.WriteString("Or export non-interactively:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# Export a generated theme\n")
	b.WriteString("omarchy-themegen --image <path-to-image> --name <theme-name> --direction <1|2|3>\n\n")
	b.WriteString("# Export with overwrite confirmation\n")
	b.WriteString("omarchy-themegen --image <path-to-image> --name <theme-name> --direction 1 --yes\n\n")
	b.WriteString("# Export a light theme\n")
	b.WriteString("omarchy-themegen --image <path-to-image> --name <theme-name> --direction 1 --light\n\n")
	b.WriteString("# Export as archive\n")
	b.WriteString("omarchy-themegen --image <path-to-image> --name <theme-name> --direction 1 --archive --archive-path ./mytheme.tar.gz\n")
	b.WriteString("```\n\n")

	b.WriteString("## Installation\n\n")
	b.WriteString("Move or copy this theme directory to:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("cp -r %s ~/.config/omarchy/themes/\n", tm.NormalizedName))
	b.WriteString("```\n\n")

	b.WriteString("## Apply\n\n")
	b.WriteString("Once installed, apply this theme with Omarchy:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("omarchy theme set %s\n", tm.NormalizedName))
	b.WriteString("```\n\n")
	b.WriteString("Note: theme application is separate from export. Use `omarchy theme set` to apply.\n\n")

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("Generated at %s UTC\n", time.Now().UTC().Format(time.RFC3339)))

	return b.String()
}
